version: 2
jobs:
  build:
    working_directory: ~/reviews
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm watch
      - run: npm test
